site_name: Alloy (Python)
site_description: Python for logic. English for intelligence.
site_url: https://docs.alloy.fyi/
repo_url: https://github.com/lydakis/alloy
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - toc.follow
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  logo: assets/logo.svg
  favicon: assets/favicon.svg
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            members_order: source
            separate_signature: true
            filters: ["!^_"]
  - gen-files:
      scripts:
        - gen_linkset.py
  - llmstxt:
      full_output: llms-full.txt
      sections:
        "Overview":
          - index.md: Intro
          - whats-new.md: What's New
          - equivalence.md: Equivalence
        "Tutorial":
          - tutorial/index.md: Tutorial (10 minutes)
        "Guides":
          - guide/core-concepts.md: Core Concepts
          - guide/commands.md: Commands
          - guide/structured-outputs.md: Structured Outputs
          - guide/tools-and-workflows.md: Tools & Workflows
          - guide/contracts.md: Contracts
          - guide/configuration.md: Configuration
          - guide/providers.md: Providers
          - guide/production.md: Production
          - guide/streaming.md: Streaming
          - guide/pitfalls.md: Common Pitfalls
          - typing.md: Typing
          - observability.md: Observability
          - tool_recipes.md: Tool Recipes
          - cookbook.md: Cookbook
          - contributing-docs.md: Contributing Docs
          - roadmap.md: Roadmap
        "Examples":
          - examples/index.md: Examples Index
          - examples/exploration.md: Exploration
          - examples/commands.md: Commands
          - examples/tools.md: Tools
          - examples/workflows.md: Workflows
          - examples/integration.md: Integration
        "API":
          - api/**/*.md
        "Architecture":
          - architecture/overview.md: Architecture Overview
          - architecture/command-lifecycle.md: Command Lifecycle
          - architecture/provider-abstraction.md: Provider Abstraction
          - architecture/type-system.md: Type System
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
extra_css:
  - assets/theme.css
extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - assets/mermaid-init.js
# (Removed Copy curl UI assets)
nav:
  - Overview:
      - index.md
      - whats-new.md
      - equivalence.md
  - Tutorial:
      - tutorial/index.md
  - Guide:
      - guide/core-concepts.md
      - guide/commands.md
      - guide/structured-outputs.md
      - guide/tools-and-workflows.md
      - guide/contracts.md
      - guide/configuration.md
      - guide/providers.md
      - guide/production.md
      - guide/streaming.md
      - guide/pitfalls.md
      - typing.md
      - observability.md
      - tool_recipes.md
  - API Reference:
      - Top-level: api/alloy.md
      - Ask: api/ask.md
      - Command: api/command.md
      - Config: api/config.md
      - Tools: api/tool.md
      - Errors: api/errors.md
      - Types: api/types.md
      - Models:
          - Base: api/models/base.md
          - OpenAI: api/models/openai.md
          - Anthropic: api/models/anthropic.md
          - Gemini: api/models/gemini.md
          - Ollama: api/models/ollama.md
  - Examples:
      - examples/index.md
      - examples/exploration.md
      - examples/commands.md
      - examples/tools.md
      - examples/workflows.md
      - examples/integration.md
  - Architecture:
      - architecture/overview.md
      - architecture/command-lifecycle.md
      - architecture/provider-abstraction.md
      - architecture/type-system.md
  - Roadmap: roadmap.md
  - Contributing Docs: contributing-docs.md
