site_name: Alloy (Python)
site_description: Python for logic. English for intelligence.
site_url: https://docs.alloy.fyi/
repo_url: https://github.com/lydakis/alloy
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.sections
    - toc.follow
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  logo: assets/logo.svg
  favicon: assets/favicon.svg
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: false
            members_order: source
            separate_signature: true
            filters: []
  - gen-files:
      scripts:
        - gen_linkset.py
  - llmstxt:
      full_output: llms-full.txt
      sections:
        "Overview":
          - index.md: Intro
          - getting-started.md: Getting Started
        "Guides":
          - configuration.md: Configuration
          - commands.md: Commands & Tools
          - equivalence.md: Equivalence Guide
          - tool_recipes.md: Tool Recipes
          - typing.md: Typing
          - backends.md: Backends & Routing
          - cookbook.md: Cookbook
          - outputs.md: Enforcing Outputs
          - examples.md: Examples
          - contributing-docs.md: Contributing Docs
          - roadmap.md: Roadmap
          - whats-new.md: What's New
        "API":
          - api/**/*.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
extra_css:
  - assets/theme.css
# (Removed Copy curl UI assets)
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - Commands & Tools: commands.md
  - Equivalence Guide: equivalence.md
  - Tool Recipes: tool_recipes.md
  - Typing: typing.md
  - Backends & Routing: backends.md
  - Cookbook: cookbook.md
  - Enforcing Outputs: outputs.md
  - Stability & Support: stability.md
  - Examples: examples.md
  - Roadmap: roadmap.md
  - What's New: whats-new.md
  - API Reference:
      - Top-level: api/alloy.md
      - Commands: api/command.md
      - Ask: api/ask.md
      - Config: api/config.md
      - Tools: api/tool.md
      - Errors: api/errors.md
      - Types: api/types.md
      - Models:
          - Base: api/models/base.md
          - OpenAI: api/models/openai.md
          - Anthropic: api/models/anthropic.md
          - Gemini: api/models/gemini.md
          - Ollama: api/models/ollama.md
  - Contributing Docs: contributing-docs.md
