site_name: Alloy (Python)
site_description: Python for logic. English for intelligence.
site_url: https://lydakis.github.io/alloy/
repo_url: https://github.com/lydakis/alloy
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - toc.follow
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  logo: assets/logo.svg
  favicon: assets/favicon.svg
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: false
            members_order: source
            separate_signature: true
            filters: []
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - Commands & Tools: commands.md
  - Backends & Routing: backends.md
  - Enforcing Outputs: outputs.md
  - Examples: examples.md
  - What's New: whats-new.md
  - API Reference:
      - Top-level: api/alloy.md
      - Commands: api/command.md
      - Ask: api/ask.md
      - Config: api/config.md
      - Tools: api/tool.md
      - Errors: api/errors.md
      - Types: api/types.md
      - Models:
          - Base: api/models/base.md
          - OpenAI: api/models/openai.md
          - Anthropic: api/models/anthropic.md
          - Gemini: api/models/gemini.md
          - Ollama: api/models/ollama.md
  - Contributing Docs: contributing-docs.md
