name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please provide enough detail to reproduce.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened? What did you expect?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal, reproducible steps (code snippet or commands).
      placeholder: |
        1. Setup ...
        2. Run ...
        3. Observe ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior and logs
      description: Include full tracebacks/logs if available. Redact secrets.
      render: text
  - type: input
    id: version
    attributes:
      label: alloy-ai version
      placeholder: 0.1.4
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: 3.10 / 3.11 / 3.12 / 3.13
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 14, Ubuntu 22.04, Windows 11
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I tried on latest main or latest release
        - label: I can reproduce with a minimal example
        - label: I searched existing issues
