name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-asyncio
      - name: Run tests
        run: |
          python -m pytest -q

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff black mypy pre-commit
      - name: Ruff
        run: |
          ruff .
      - name: Black (check)
        run: |
          black --check .
      - name: Mypy
        run: |
          mypy .
      - name: Pre-commit (all files)
        run: |
          pre-commit run --all-files --show-diff-on-failure
