name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    name: Python ${{ matrix.python-version }} — fast checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Lint, typecheck, tests (fast + coverage)
        run: make ci-fast
